
# optional. If you have already defined connection. you can comment it.
connections:
  - name: postgre_2
    url: jdbc:postgresql://localhost/lauda
    username: lauda
    password: lauda
    class_name: org.postgresql.Driver
  - name: postgre_3
    url: jdbc:postgresql://localhost/lauda
    username: lauda
    password: lauda
    class_name: org.postgresql.Driver
  - name: oracle_1
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: lauda
    password: lauda
    class_name: oracle.jdbc.driver.OracleDriver
  - name: oracle_2
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: laudax
    password: lauda
    class_name: oracle.jdbc.driver.OracleDriver


# Required. You can skip optional fields. See [name=table_4] for only adding columns.
mappings:
  - name: source_table_2
    source_connection: oracle_1
    target_connection: postgre_2
    source_table: source_table_2
    target_table: target_table_2
    source_columns: [owner, table_name, pct_free, last_analyzed]
    target_columns: [owner, table_name, pct_free, last_analyzed]
    source_hint: /*+ parallel(16) */
    target_hint: /*+ nologging */
    filter: owner = 'SYS'
    batch_size: 10
    drop_create: false

  - name: table_3
    source_connection: oracle_1
    target_connection: postgre_2
    source_table: source_table_3
    target_table: target_table_3
    source_columns: [owner, table_name]
    target_columns: [owner, table_name]

    # this will add given columns only, mapping should exists already
  - name: table_3
    source_columns: [last_analyzed]
    target_columns: [last_analyzed]

